// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImProto.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PackageCategory

typedef GPB_ENUM(PackageCategory) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  PackageCategory_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PackageCategory_Ping = 0,
  PackageCategory_Login = 1,
  PackageCategory_Logout = 2,
  PackageCategory_SendToUser = 3,
  PackageCategory_SendToChannel = 4,
  PackageCategory_ReceivedUserMsg = 5,
  PackageCategory_ReceivedChannelMsg = 6,
  PackageCategory_BindToChannel = 7,
  PackageCategory_UnbindToChannel = 8,
  PackageCategory_BindToGroup = 9,
  PackageCategory_UnbindToGroup = 10,
  PackageCategory_SendToGroup = 11,
  PackageCategory_ReceivedGroupMsg = 12,
  PackageCategory_Result = 99,
  PackageCategory_AdminSend = 199,
  PackageCategory_SubUserLogin = 200,
  PackageCategory_UnsubUserLogin = 201,
  PackageCategory_PubUserLogin = 202,
};

GPBEnumDescriptor *PackageCategory_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL PackageCategory_IsValidValue(int32_t value);

#pragma mark - Enum ResultCode

typedef GPB_ENUM(ResultCode) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  ResultCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ResultCode_Success = 0,
  ResultCode_NeedLogin = 1,
  ResultCode_AuthFailed = 2,
};

GPBEnumDescriptor *ResultCode_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL ResultCode_IsValidValue(int32_t value);

#pragma mark - ImProtoRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ImProtoRoot : GPBRootObject
@end

#pragma mark - SocketPackage

typedef GPB_ENUM(SocketPackage_FieldNumber) {
  SocketPackage_FieldNumber_Seq = 1,
  SocketPackage_FieldNumber_Category = 2,
  SocketPackage_FieldNumber_Content = 3,
};

@interface SocketPackage : GPBMessage

@property(nonatomic, readwrite) int32_t seq;

@property(nonatomic, readwrite) PackageCategory category;

@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@end

/// Fetches the raw value of a @c SocketPackage's @c category property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SocketPackage_Category_RawValue(SocketPackage *message);
/// Sets the raw value of an @c SocketPackage's @c category property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSocketPackage_Category_RawValue(SocketPackage *message, int32_t value);

#pragma mark - SocketResult

typedef GPB_ENUM(SocketResult_FieldNumber) {
  SocketResult_FieldNumber_Category = 1,
  SocketResult_FieldNumber_Code = 2,
  SocketResult_FieldNumber_Message = 3,
  SocketResult_FieldNumber_UserTags = 4,
};

@interface SocketResult : GPBMessage

@property(nonatomic, readwrite) PackageCategory category;

@property(nonatomic, readwrite) ResultCode code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

@end

/// Fetches the raw value of a @c SocketResult's @c category property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SocketResult_Category_RawValue(SocketResult *message);
/// Sets the raw value of an @c SocketResult's @c category property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSocketResult_Category_RawValue(SocketResult *message, int32_t value);

/// Fetches the raw value of a @c SocketResult's @c code property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SocketResult_Code_RawValue(SocketResult *message);
/// Sets the raw value of an @c SocketResult's @c code property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSocketResult_Code_RawValue(SocketResult *message, int32_t value);

#pragma mark - LoginToken

typedef GPB_ENUM(LoginToken_FieldNumber) {
  LoginToken_FieldNumber_UserId = 1,
  LoginToken_FieldNumber_Token = 2,
  LoginToken_FieldNumber_VersionCode = 3,
  LoginToken_FieldNumber_Appkey = 4,
  LoginToken_FieldNumber_IsAdmin = 5,
  LoginToken_FieldNumber_VersionName = 6,
};

@interface LoginToken : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite) int32_t versionCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appkey;

@property(nonatomic, readwrite) BOOL isAdmin;

@property(nonatomic, readwrite, copy, null_resettable) NSString *versionName;

@end

#pragma mark - SendUserMessage

typedef GPB_ENUM(SendUserMessage_FieldNumber) {
  SendUserMessage_FieldNumber_Receiver = 1,
  SendUserMessage_FieldNumber_Type = 2,
  SendUserMessage_FieldNumber_Content = 3,
  SendUserMessage_FieldNumber_UserTags = 4,
  SendUserMessage_FieldNumber_Sender = 5,
};

@interface SendUserMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *receiver;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

///  used for admin
@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@end

#pragma mark - ReceivedUserMessage

typedef GPB_ENUM(ReceivedUserMessage_FieldNumber) {
  ReceivedUserMessage_FieldNumber_MsgId = 1,
  ReceivedUserMessage_FieldNumber_Sender = 2,
  ReceivedUserMessage_FieldNumber_Type = 3,
  ReceivedUserMessage_FieldNumber_Content = 4,
  ReceivedUserMessage_FieldNumber_UserTags = 5,
  ReceivedUserMessage_FieldNumber_SendTime = 6,
};

@interface ReceivedUserMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

@property(nonatomic, readwrite) int32_t sendTime;

@end

#pragma mark - SendChannelMessage

typedef GPB_ENUM(SendChannelMessage_FieldNumber) {
  SendChannelMessage_FieldNumber_ChannelId = 1,
  SendChannelMessage_FieldNumber_Type = 2,
  SendChannelMessage_FieldNumber_Content = 3,
  SendChannelMessage_FieldNumber_UserTags = 4,
  SendChannelMessage_FieldNumber_Sender = 5,
};

@interface SendChannelMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

///  used for admin
@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@end

#pragma mark - ReceivedChannelMessage

typedef GPB_ENUM(ReceivedChannelMessage_FieldNumber) {
  ReceivedChannelMessage_FieldNumber_MsgId = 1,
  ReceivedChannelMessage_FieldNumber_Sender = 2,
  ReceivedChannelMessage_FieldNumber_ChannelId = 3,
  ReceivedChannelMessage_FieldNumber_Type = 4,
  ReceivedChannelMessage_FieldNumber_Content = 5,
  ReceivedChannelMessage_FieldNumber_UserTags = 6,
  ReceivedChannelMessage_FieldNumber_SendTime = 7,
};

@interface ReceivedChannelMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

@property(nonatomic, readwrite) int32_t sendTime;

@end

#pragma mark - Channel

typedef GPB_ENUM(Channel_FieldNumber) {
  Channel_FieldNumber_ChannelId = 1,
};

@interface Channel : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@end

#pragma mark - UserGroup

typedef GPB_ENUM(UserGroup_FieldNumber) {
  UserGroup_FieldNumber_UserId = 1,
  UserGroup_FieldNumber_GroupIdsArray = 2,
};

@interface UserGroup : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *groupIdsArray;
/// The number of items in @c groupIdsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger groupIdsArray_Count;

@end

#pragma mark - SendGroupMessage

typedef GPB_ENUM(SendGroupMessage_FieldNumber) {
  SendGroupMessage_FieldNumber_GroupId = 1,
  SendGroupMessage_FieldNumber_Type = 2,
  SendGroupMessage_FieldNumber_Content = 3,
  SendGroupMessage_FieldNumber_UserTags = 4,
  SendGroupMessage_FieldNumber_Sender = 5,
};

@interface SendGroupMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

///  used for admin	
@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@end

#pragma mark - ReceivedGroupMessage

typedef GPB_ENUM(ReceivedGroupMessage_FieldNumber) {
  ReceivedGroupMessage_FieldNumber_MsgId = 1,
  ReceivedGroupMessage_FieldNumber_Sender = 2,
  ReceivedGroupMessage_FieldNumber_GroupId = 3,
  ReceivedGroupMessage_FieldNumber_Type = 4,
  ReceivedGroupMessage_FieldNumber_Content = 5,
  ReceivedGroupMessage_FieldNumber_UserTags = 6,
  ReceivedGroupMessage_FieldNumber_SendTime = 7,
};

@interface ReceivedGroupMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *userTags;
/// The number of items in @c userTags without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userTags_Count;

@property(nonatomic, readwrite) int32_t sendTime;

@end

#pragma mark - AdminMessage

typedef GPB_ENUM(AdminMessage_FieldNumber) {
  AdminMessage_FieldNumber_Receiver = 1,
  AdminMessage_FieldNumber_Category = 2,
  AdminMessage_FieldNumber_MessageContent = 3,
};

@interface AdminMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *receiver;

@property(nonatomic, readwrite) PackageCategory category;

@property(nonatomic, readwrite, copy, null_resettable) NSData *messageContent;

@end

/// Fetches the raw value of a @c AdminMessage's @c category property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t AdminMessage_Category_RawValue(AdminMessage *message);
/// Sets the raw value of an @c AdminMessage's @c category property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetAdminMessage_Category_RawValue(AdminMessage *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
